name: CI_DEPLOY_Pipeline
on: 
  push:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  CheckPipelineCriteria:
    runs-on: ubuntu-latest
    steps:
      - name: "getting pipeline context values..."
        run: |
          echo "pipeline was triggered by event :" ${{ github.event_name }} 
          echo "pipeline is based on remote branch :" ${{github.ref_name}} 
      - name: "checking if pipeline criteria is met ..."
        if: |
          github.event_name == 'workflow_dispatch' && 
          github.ref_name != 'develop'
        run: |
         echo "This pipeline supports deployment only from develop branch. Probably the selected branch is not develop ,hence exiting..."
         exit 1


  DeployChanges:
    needs: CheckPipelineCriteria    
    runs-on: ubuntu-latest
    steps:
      # Setup the runner environment
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: setup the runner
        uses: ./.github/actions/setup-sfdx-runner
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET_SFORG_cienviron }} 
       
       # Prepare , validate and deploy the delta package   
      - name: "create delta package for changes in Develop compared to Main branch..."
        run: |          
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all
          git --no-pager diff --name-status develop origin/main
          sfdx sgd:source:delta --to develop --from origin/main --source force-app --repo . --output .
          cat package/package.xml
          echo "--- destructiveChanges.xml generated with deleted metadata ---"
          cat destructiveChanges/destructiveChanges.xml

      - name: "validating changes in Develop branch compared to Main branch with full test run against the CI environment..."
        run: |
          VALIDATION_JOB=$(sfdx force:source:deploy -x package/package.xml --testlevel=RunLocalTests --checkonly --wait 30)
          echo "$VALIDATION_JOB"
          echo "::set-output name=VALIDATION_JOB_ID::$VALIDATION_JOB"          
          echo "validating the deletion of removed metadata..."
          sfdx force:mdapi:deploy -d destructiveChanges --ignorewarnings --testlevel=RunLocalTests --checkonly --wait -1
        id: validate-id
      - name: "deploying changes in Develop branch compared to Main branch in the CI environment with no test run..."
        run: |
          sfdx force:source:deploy -x package/package.xml --testlevel=NoTestRun --wait 30
          # echo "quick deploying the changes validated in ${{steps.validate-id.outputs.VALIDATION_JOB_ID}}"
          echo "deleting removed metadata..."
          sfdx force:mdapi:deploy -d destructiveChanges --ignorewarnings --testlevel=NoTestRun --wait -1          