name: CIPipeline_Deploy
on: 
  push:
    branches:
      - 'develop'
  workflow_dispatch:
env:
  BRANCH_NAME: 'dummy'

jobs:
  CheckPipelineCriteria:
    runs-on: ubuntu-latest
    steps:
      - name: "get context values"
        run: |
         echo "env.BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})"
         echo "Trigger Event : ${{github.event_name}}"
      - name: "check pipeline criteria"
        if: |
          github.event_name == 'workflow_dispatch' && 
          env.BRANCH_NAME != 'develop'
        run: |
         echo "crtiteria not met to run this deployment,hence exiting..."
         exit 1


  DeployChangesForCI:
    needs: CheckPipelineCriteria    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET_SFORG_cienviron }}
      - name: "Install NodeApp and create delta package for changes in Develop compared to Main branch"
        run: |
          sudo npm install sfdx-git-delta@latest -g
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all
          git --no-pager diff --name-status develop origin/main
          sgd --to develop --from origin/main --repo . --output .
          cat package/package.xml     
      - name: "Deploy changes in Develop branch compared to Main branch"
        run: sfdx force:source:deploy -x package/package.xml --testlevel=RunLocalTests -w30
