name: CIPipeline_Deploy
on: 
  push:
    branches:
      - 'develop'
  workflow_dispatch:
    inputs:
      tags:
        description: 'DEVELOP ONLY'

jobs:
  ValidateCriteria:
    runs-on: ubuntu-latest
    steps:
      - name: "Get the branch name into BRANCH_NAME variable"
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"      
      - name: "Get the event which triggered the pipeline into PIPELINE_EVENT_NAME variable"
        run: echo "::set-env name=PIPELINE_EVENT_NAME::$(echo ${github.event_name})"
      - name: "Criteria met ?"
        run: |
         echo "::set-env name=CRITERIA_MET::${{true}}"        
         if: (PIPELINE_EVENT_NAME == 'workflow_dispatch' && BRANCH_NAME != 'develop')
         echo "::set-env name=CRITERIA_MET::${{false}}"
         exit 1


  DeployChangesForCI:
    needs: ValidateCriteria    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET_SFORG_cienviron }}
      - name: "Install NodeApp and create delta package for changes in Develop compared to Main branch"
        run: |
          sudo npm install sfdx-git-delta@latest -g
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all
          git --no-pager diff --name-status develop origin/main
          sgd --to develop --from origin/main --repo . --output .
          cat package/package.xml     
      - name: "Deploy changes in Develop branch compared to Main branch"
        run: sfdx force:source:deploy -x package/package.xml --testlevel=RunLocalTests -w30