name: QA_DEPLOY_Pipeline
on: 
  push:
    branches:
      - 'release'
  workflow_dispatch:

jobs:
  CheckPipelineCriteria:
    runs-on: ubuntu-latest
    steps:
      - name: "getting pipeline context values..."
        run: |
          echo "pipeline was triggered by event :" ${{ github.event_name }} 
          echo "pipeline is based on remote branch :" ${{github.ref_name}} 
      - name: "checking if pipeline criteria is met ..."
        if: |
          github.event_name == 'workflow_dispatch' && 
          github.ref_name != 'release'
        run: |
         echo "This pipeline supports deployment only from release branch. Probably the selected branch is not release ,hence exiting..."
         exit 1


  DeployChanges:
    needs: CheckPipelineCriteria    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET_SFORG_QAENVIRON }}
      - name: "installing nodeapp and creating delta package for changes in Release branch compared to Main branch..."
        run: |
          sudo npm install sfdx-git-delta@latest -g
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all
          git --no-pager diff --name-status release origin/main
          sgd --to release --from origin/main --repo . --output .
          cat package/package.xml 
          echo "--- destructiveChanges.xml generated with deleted metadata ---"
          cat destructiveChanges/destructiveChanges.xml    
      - name: "validating changes in Release branch compared to Main branch with full test run against the QA environment..."
        run: |
          sfdx force:source:deploy -x package/package.xml --testlevel=RunLocalTests --checkonly --wait 30
          echo "validating the deletion of removed metadata..."
          sfdx force:mdapi:deploy -d destructiveChanges --ignorewarnings --testlevel=RunLocalTests --checkonly --wait -1
      - name: "deploying changes in Release branch compared to Main branch in the QA environment..."
        run: |
          sfdx force:source:deploy -x package/package.xml --testlevel=NoTestRun --wait 30
          echo "deleting removed metadata..."
          sfdx force:mdapi:deploy -d destructiveChanges --ignorewarnings --testlevel=NoTestRun --wait -1          