name: RELEASE_PullRequestValidation_PipeLine
on: 
  pull_request:
    types: [opened, reopened]
    branches:
     - 'release'
jobs:
  ValidatePullRequest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pipeline was triggered by event :" ${{ github.event_name }} 
      - run: echo "pipeline is based on remote branch :" ${{github.ref_name}} 
    # Setup the runner environment
      - name: checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: setup the runner
        uses: ./.github/actions/setup-sfdx-runner
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET_SFORG_qaenviron }}  
    # Prepare , validate and deploy the delta package
      - name: "creating delta package for validation..."
        run: |          
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all
          git checkout -b pr
          git --no-pager diff --name-status pr origin/release
          sfdx sgd:source:delta --to pr --from origin/release --source force-app --repo . --output .
          cat package/package.xml     
      - name: "running validation of pull request against QA environment with full test run..."
        run: sfdx force:source:deploy -x package/package.xml --checkonly --testlevel=RunLocalTests -w 30